# Generated by Django 5.2.9 on 2026-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_unit_bulk_name_product_unit_retail_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('CREDIT', 'Credit')], max_length=10),
        ),
    ]
