# Generated by Django 5.2.9 on 2026-08-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_transaction_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_per_kilo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_per_sack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
