# Generated by Django 5.2.9 on 2026-09-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_seed_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('CREDIT', 'Credit'), ('DEBT_PAYMENT', 'Debt Payment')], max_length=20),
        ),
    ]
