# Generated by Django 5.2.9 on 2026-09-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_per_bulk',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=10, null=True),
        ),
    ]
